id: P329666C5
initial_creation_type: input
source_metadata:
  Title: Aṣṭasāhasrikā prajñāpāramitā
  Editor: Vaidya, P. L.
  Publisher: The Mithila Institute of Post-Graduate Studies and Research in Sanskrit
    Learning
  Place of Publication: Darbhanga
  Year: '1960'
  1 sarvākārajñatācaryā prathamaḥ parivartaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  2 śakraparivarto dvitīyaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  3 aprameyaguṇadhāraṇapāramitāstūpasatkāraparivartastṛtīyaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  4 guṇaparikīrtanaparivartaścaturthaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  5 puṇyaparyāyaparivartaḥ pañcamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  6 anumodanāpariṇāmanāparivartaḥ ṣaṣṭhaḥ|:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  7 nirayaparivartaḥ saptamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  8 viśuddhiparivarto'ṣṭamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  9 stutiparivarto navamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  10 dhāraṇaguṇaparikīrtanaparivarto daśamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  11 mārakarmaparivarta ekādaśaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  12 lokasaṃdarśanaparivarto dvādaśaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  13 acintyaparivartastrayodaśaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  14 aupamyaparivartaścaturdaśaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  15 devaparivartaḥ pañcadaśaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  16 tathatāparivartaḥ ṣoḍaśaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  17 avinivartanīyākāraliṅganimittaparivartaḥ saptadaśaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  18 śūnyatāparivarto'ṣṭādaśaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  19 gaṅgadevībhaginīparivarta ekonaviṃśaḥ|:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  20 upāyakauśalyamīmāṃsāparivarto viṃśatitamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  21 mārakarmaparivarta ekaviṃśatitamaḥ|:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  22 kalyāṇamitraparivarto dvāviṃśatitamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  23 śakraparivartastrayoviṃśatitamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  24 abhimānaparivartaścaturviṃśatitamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  25 śikṣāparivartaḥ pañcaviṃśatitamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  26 māyopamaparivartaḥ ṣaḍviṃśatitamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  27 sāraparivartaḥ saptaviṃśatitamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  28 avakīrṇakusumaparivarto'ṣṭāviṃśatitamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  29 anugamaparivarta ekonatriṃśattamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  30 sadāpraruditaparivartastriṃśattamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  31 dharmodgataparivarta ekatriṃśattamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  32 parīndanāparivarto dvātriṃśattamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:10:18.772491'
last_modified_at: '2022-03-08T16:10:18.772502'
